### ISSUE TITLE
`fu 1` returns "fu: Error invalid index number!"

### ISSUE THREAD

**Issue by eoinoc** [samirahmed/fu#1]
I just installed fu by cloning and making. Really cool.

Let's say I run `fu mysql` some results are shown.

I immediately follow that with the next command `fu 1` but I'm told **"fu: Error invalid index number!"**.

Am I doing something wrong?

**Comment by samirahmed** [comment]
I don't think that you are doing anything wrong.

My best guess would be that you are running linux and the copy function is not working. 

As it is, fu returns that error message when it tries to copy to clipboard

So here are a few litmus test you can do

---

Try to make sure the unit tests are working, you can run all of them but I would first try (make platform and then make dotfile)

`cd fu/src/lib/test/`

`make platform`

Platform should copy "words I want on the clipboard" to your clipboard and open commandlinefu.com for you.

Try to ctrl-v and see if you wrote to clipboard or if you get an exception

The output should be

```
Platform Utility Test --------------

Copied to clipboard : words i want on the clipboard
```

If platform is the problem, it could be that you don't have `xclip` installed on your linux box? 
Let me know what os you are using and I will try to find a solution

---

If not try

`make dotfile`

If platform isn't the problem, try make dotfile and ensure the output is 

```
Dotfile Tests --------------------------

File Exists? True
Wrote Sample JSON to dotfile
File Read is same as original!
Saving copy command
Command Saved and Loaded Successfully? Yes
History Save Loaded Succesful? True
```

If you are getting an error here, try

`cat ~/.fu`

and see if you have an output with json in it.

Let me know and I will try and narrow down what the problem is.

**Comment by hrishimittal** [comment]
I had the same error on Ubuntu. I didn't have xclip, but installing that didn't fix it (I even reinstalled fu after installing xclip).

When I run make platform I get the following error:

python platform_test.py "words i want on the clipboard"

Platform Utility Test --------------

Traceback (most recent call last):
  File "platform_test.py", line 10, in <module>
    my_system = system()
  File "/home/hrishi/code/fu/src/lib/platform_utils.py", line 21, in **init**
    elif 'cygwin' in info.lower():
AttributeError: 'set' object has no attribute 'lower'
make: **\* [platform] Error 1

**Comment by eoinoc** [comment]
Yes, as @hrishimittal said, running `make platform` gives that error. Yes, I'm on Linux.

**Comment by samirahmed** [comment]
okay it looks like it might just be that  .lower() needs to be removed

I don't have a linux computer infront of me, but if you could try

`cd fu`

`sudo make uninstall`

`cd src/lib/`

open platform_utils.py and remove the `.lower()` so that line 21 reads 

`elif 'cygwin' in info:`

save and 

`cd /path/to/fu`

`sudo make install`

I believe that might fix it for linux users, if so I will push a fix

**Comment by samirahmed** [comment]
try to uninstall

`sudo make unistall`

and repeat the install process but clone the new repo,

let me know if that works

**Comment by samirahmed** [comment]
Linux compatibility should be fixed by this [pull request from benvd](https://github.com/samirahmed/fu/pull/4)

Just uninstall, pull and reinstall.

**Comment by eoinoc** [comment]
Yes, thanks to @samirahmed and @benvd . The pull request fixed it.

I just had to also install xclip:

```
sudo apt-get install xclip
```
